# Generated by Django 3.1.2 on 2022-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'BUSADMIN'), (2, 'BUS TERMINUS ADMIN'), (3, 'PASSENGER')], null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
