# Generated by Django 3.2.11 on 2022-01-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_newuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='role',
            new_name='group',
        ),
    ]
