# Generated by Django 3.2.11 on 2022-01-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_role_newuser_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='group',
            new_name='role',
        ),
    ]
