# Generated by Django 3.2.11 on 2022-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_group_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'bus_admin'), (2, 'bus_terminus_admin'), (3, 'passenger')], null=True),
        ),
    ]
