# Generated by Django 3.2.11 on 2022-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bus_admin'), (2, 'bus_terminus_admin'), (3, 'passenger'), (4, 'superuser')], default=4),
        ),
    ]
