# Generated by Django 3.1.2 on 2022-01-05 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('destination_from', models.CharField(max_length=127)),
                ('destination_to', models.CharField(max_length=127)),
                ('date_of_departure', models.DateField(default=django.utils.timezone.now)),
                ('time_of_departure', models.TimeField(default=django.utils.timezone.now)),
                ('date_of_arrival', models.DateField(default=django.utils.timezone.now)),
                ('time_of_arrival', models.TimeField(default=django.utils.timezone.now, help_text='Enter estimated time')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivername', to='bus.driver')),
            ],
        ),
    ]
