# Generated by Django 3.1.2 on 2022-01-04 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date_of_departure',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_of_arrival',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Enter estimated time'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_of_departure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
